version: 1.0.{build}

# branches to build
branches:
  # white list
  only:
    - develop_appveyor

clone_folder: c:\dev\openMVG

install:
  - git submodule update --init --recursive

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 14 2015"

build_script:
  - cd c:\dev\openMVG
  - md openMVG_build
  - cd openMVG_build
  - cmake -G"%GENERATOR%" -DOpenMVG_BUILD_EXAMPLES=OFF -DOpenMVG_BUILD_TESTS=ON ../src/
  #Build only some targets since there is no time to compile all
  - cmake --build . --config Debug --target openMVG_test_sequential_SfM
  #- cmake --build . --config Debug --target openMVG_test_global_SfM
  #- cmake --build . --config Debug --target openMVG_main_IncrementalSfM
  #- cmake --build . --config Debug --target openMVG_main_GlobalSfM

build:
  parallel: true
  verbosity: minimal

