version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - develop_appveyor

clone_folder: c:\dev\openMVG

install:
  - git submodule update --init --recursive
  
build_script:
  - cd c:\dev\openMVG
  - md openMVG_build
  - cd openMVG_build
  - cmake -G"Visual Studio 14 2015 Win64" -DOpenMVG_BUILD_EXAMPLES=OFF ../src/
  - cmake --build . --target ALL_BUILD --config Debug

build:
  parallel: true
  verbosity: minimal
  project: ALL_BUILD.vcxproj


after_build:
  - cmd: cmake --build C:\dev\openMVG\openMVG_build --target RUN_TESTS --config Release


