version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - develop_appveyor

clone_folder: c:\dev\openMVG

install:
  - git submodule update --init --recursive

environment:
  matrix:
    # - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "MinGW Makefiles"
      COMPILER_PATH: C:\MinGW\bin

before_build:
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=%COMPILER_PATH%;%PATH%

build_script:
  - cd c:\dev\openMVG
  - md openMVG_build
  - cd openMVG_build
  - cmake -G"%GENERATOR%" -DOpenMVG_BUILD_EXAMPLES=OFF ../src/
  - cmake --build . --target ALL_BUILD --config Debug

build:
  parallel: true
  verbosity: minimal
  project: ALL_BUILD.vcxproj

